app:
  name: file-watch-demo
  version: 1.0.3
  debug: true

server:
  host: 0.0.0.0
  port: 1000

database:
  host: localhost
  port: 3306
  username: root
  password: secret123

log:
  level: debug
  format: json

