app:
  name: notification-demo
  version: 1.0.0

server:
  host: 0.0.0.0
  port: 9090

database:
  host: prod-db.example.com
  port: 3307
  password: new-super-secret-password

cache:
  ttl: 600

log:
  level: debug
