app:
  name: example-app
  version: 1.0.0
  debug: true

server:
  host: 0.0.0.0
  port: 8080
  timeout: 30.5
  allowed_hosts:
    - localhost
    - 127.0.0.1
    - example.com

database:
  host: localhost
  port: 3306
  username: root
  password: secret123
  database: example_db

log:
  level: debug
  format: json
  output: stdout

# 新增字段用于校验示例
contact:
  email: admin@example.com
  phone: "+86-138-0013-8000"

api:
  base_url: https://api.example.com
  timeout: 30
  retry_count: 3

security:
  jwt_secret: "your-super-secret-jwt-key-here"
  session_timeout: 3600

