app:
  name: my-awesome-app
  version: 1.0.0
  env: development

server:
  host: 0.0.0.0
  port: 8080

database:
  host: localhost
  port: 3306
  username: root
  database: myapp

cache:
  ttl: 300

log:
  level: info
  format: json

